### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii-3DS#18]
There is a few UI changes TBD.
- [x] Description on app page
- [ ] Rating in app list and app page
- [ ] Possibility to scroll the app description text.
- [ ] Visual scrollbar (1.1.0.0/1.2.0.0)

**Comment by lukas2511** [comment]
Would be great to also have screenshots or even videos (may be too much) for the apps, longer descriptions (like have a short one as introduction, but have more details available if somebody is interested), update notes, all that kind of stuff. Also links to forum threads / release pages and sourcecode, or whatever.
