### ISSUE TITLE
Rewrite the UI code

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii-3DS#22]
The gui code is darn messy and should indeed be re-coded.

**Comment by thejsa** [comment]
I think buttons need to show that they're being pressed, maybe they darken while the tap is being held and activates when the tap is released?

**Comment by filfat** [comment]
Possibly code a stand-alone GUI library with button support and such.

**Comment by thejsa** [comment]
Sounds like a good idea, then it could be used by other homebrew.

On 04/02/2015, Filiph Sandström <notifications@github.com> wrote:
> Possibly code a stand-alone GUI library with button support and such.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DownloadMii/DownloadMii/issues/22#issuecomment-72942725


-- 
Yours sincerely,

Joshua Kelly (aka jsa)
http://www.nonm.co.uk/
https://squashua.uk.to/

**Comment by filfat** [comment]
Working on this right now.
