### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii-3DS#29]
For the rewrite I'm thinking MIT since it's really simple.

Thoughts?

**Comment by AlexS2412** [comment]
you definitely should.ever since i saw this project come out i loved just as much as the one on the wii!i hope it turns out to be  as big of success as that one.

**Comment by thejsa** [comment]
I personally prefer the Apache License (2.0) or if I want to be very lenient the BSD 3-clause.

**Comment by filfat** [comment]
@thejsa after looking into it I have decided to switch both DownloadMii and 3ds.js to BSD 4-clause as it seems to do the job well enough :)
